<?php
$path    = __DIR__ . '/../dist/index.html';

$basePath = $this->serverUrl(rtrim($this->basePath(), '/') . '/');

$html = file_get_contents($path);

if (isset($configs)) {
    if (!isset($configs['baseUrl'])) {
        $configs['baseUrl'] = rtrim($this->url(), '/');
    }
    $html = str_replace('/*%ZFEGG_CONFIG%*/', sprintf('zfeggConfig = %s;', json_encode((object)$configs)), $html);
}

echo $html;
